/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package balance;

/**
 *
 * @author Hemmat
 */
public class MainHome extends javax.swing.JFrame {

    int auth_leve = 1;
    public MainHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        m_users = new javax.swing.JMenu();
        mi_AddUser = new javax.swing.JMenuItem();
        mi_ListUsers = new javax.swing.JMenuItem();
        m_customers = new javax.swing.JMenu();
        mi_AddCustomer = new javax.swing.JMenuItem();
        mi_showCustomer = new javax.swing.JMenuItem();
        mi_report = new javax.swing.JMenu();
        m_setting = new javax.swing.JMenu();
        mi_changeTheme = new javax.swing.JMenuItem();
        mi_about = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("jMenu5");

        jMenu6.setText("File");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar3.add(jMenu7);

        jMenu8.setText("File");
        jMenuBar4.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar4.add(jMenu9);

        jMenu11.setText("jMenu11");

        jMenu12.setText("File");
        jMenuBar5.add(jMenu12);

        jMenu13.setText("Edit");
        jMenuBar5.add(jMenu13);

        jMenu15.setText("jMenu15");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        m_users.setText("Users");

        mi_AddUser.setText("Add New User");
        mi_AddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_AddUserActionPerformed(evt);
            }
        });
        m_users.add(mi_AddUser);

        mi_ListUsers.setText("List of Users");
        mi_ListUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_ListUsersActionPerformed(evt);
            }
        });
        m_users.add(mi_ListUsers);

        jMenuBar1.add(m_users);

        m_customers.setText("Customer");

        mi_AddCustomer.setText("Add new customer");
        m_customers.add(mi_AddCustomer);

        mi_showCustomer.setText("Show all customer");
        m_customers.add(mi_showCustomer);

        mi_report.setText("Report");
        m_customers.add(mi_report);

        jMenuBar1.add(m_customers);

        m_setting.setText("Settings");

        mi_changeTheme.setText("Change Theme");
        m_setting.add(mi_changeTheme);

        mi_about.setText("About");
        m_setting.add(mi_about);

        jMenuBar1.add(m_setting);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mi_AddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_AddUserActionPerformed

      this.setVisible(false);
      Rigester r = new Rigester();
      r.setVisible(true);
      r.createdByAdmin =true;
    }//GEN-LAST:event_mi_AddUserActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        Helper.center(this);
        switch (auth_leve) {
            case 4:
                break;
            case 2:
                this.mi_AddUser.setEnabled(false);
                break;
            default:
                this.m_users.setEnabled(false);
                this.mi_AddCustomer.setEnabled(false);
                this.mi_report.setEnabled(false);
                break;
        }
    }//GEN-LAST:event_formWindowOpened

    private void mi_ListUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_ListUsersActionPerformed

        this.setVisible(false);
        new UserList().setVisible(true);
    }//GEN-LAST:event_mi_ListUsersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu m_customers;
    private javax.swing.JMenu m_setting;
    private javax.swing.JMenu m_users;
    private javax.swing.JMenuItem mi_AddCustomer;
    private javax.swing.JMenuItem mi_AddUser;
    private javax.swing.JMenuItem mi_ListUsers;
    private javax.swing.JMenuItem mi_about;
    private javax.swing.JMenuItem mi_changeTheme;
    private javax.swing.JMenu mi_report;
    private javax.swing.JMenuItem mi_showCustomer;
    // End of variables declaration//GEN-END:variables
}
