/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package balance;

import java.awt.Toolkit;

/**
 *
 * @author Hemmat
 */
public class Rigester extends javax.swing.JFrame {

  boolean createdByAdmin = false;
  
    public Rigester() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btng__auth = new javax.swing.ButtonGroup();
        tf_fullName = new javax.swing.JTextField();
        tf_username = new javax.swing.JTextField();
        pf_password = new javax.swing.JPasswordField();
        ps_confirm = new javax.swing.JPasswordField();
        jrb_admin = new javax.swing.JRadioButton();
        jEditor = new javax.swing.JRadioButton();
        btn_rigester = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        jb_user = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tf_fullName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_fullName.setToolTipText("Enter your full name");

        tf_username.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        tf_username.setToolTipText("Enter your username");

        pf_password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pf_password.setToolTipText("Type your password");

        ps_confirm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ps_confirm.setToolTipText("Confirm your password");

        btng__auth.add(jrb_admin);
        jrb_admin.setText("Admin");

        btng__auth.add(jEditor);
        jEditor.setText("Editor");

        btn_rigester.setText("Rigester");
        btn_rigester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rigesterActionPerformed(evt);
            }
        });

        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        btng__auth.add(jb_user);
        jb_user.setText("User");

        jLabel1.setText("Full-Name");

        jLabel2.setText("Confirm Password");

        jLabel3.setText("UserName");

        jLabel4.setText("Passowrd");

        jLabel5.setText("I have already registered!");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(5, 5, 5)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pf_password)
                    .addComponent(tf_username, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(tf_fullName)
                    .addComponent(ps_confirm)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jrb_admin)
                        .addGap(18, 18, 18)
                        .addComponent(jEditor)
                        .addGap(18, 18, 18)
                        .addComponent(jb_user))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_rigester, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_fullName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pf_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ps_confirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrb_admin)
                    .addComponent(jEditor)
                    .addComponent(jb_user))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_rigester)
                    .addComponent(btn_cancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
       
        System.exit(0);
        
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

      Helper.center(this);
       
    }//GEN-LAST:event_formWindowOpened

    private void btn_rigesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rigesterActionPerformed

    if(!tf_fullName.getText().isEmpty()){
        if(!tf_username.getText().isEmpty()){
            if(pf_password.getPassword().length>0){
                if(ps_confirm.getPassword().length>0){
                   
                    if(pf_password.getText().equals(ps_confirm.getText())){
                      
                   int auth = 0;
                   if( btng__auth.isSelected(jrb_admin.getModel())){
                       auth = 4;
                   }else if( btng__auth.isSelected(jEditor.getModel())){
                       auth = 2; 
                   }else if( btng__auth.isSelected(jb_user.getModel())){
                       auth = 1;
                   }else {
                     auth = 0;  
                   }
                   
                   if(auth !=0){
                       //validate done in UI
                       
                       DBConnect connect = new DBConnect();
                      try{
                         boolean res =   connect.excute("INSERT INTO users VALUES ("+null+",'"+tf_fullName.getText()+"','"+tf_username.getText()+"',PASSWORD('"+ps_confirm.getText()+"'),"+auth+")");
                         if(res ==true){
                             Helper.showNotification("you have registerd sucessfully");
                          
                             if(createdByAdmin==true){
                                 MainHome a = new MainHome();
                                 a.auth_leve = 4;
                                 this.setVisible(false);
                                 a.setVisible(true);
                             }else{
                              login l = new login();
                             this.setVisible(false);
                             l.setVisible(true);
                             }
                             
                         }
                      }catch(Exception e){
                          Helper.showNotification("the users is not registered to database");
                          
                      }
//                          this.setVisible(false);
//                        login l  =new login();
//                          l.setVisible(true); 
                   }else{
                       Helper.showNotification("Please choose your authority!");
                   }
                   
                       
                        
                    }else{
                        //do not match
                        Helper.showNotification("Password does not match!");
                    }
                    
                }else{
                    //confi
                    Helper.showNotification("Confirm Password is empty!");
                }
            }else{
                //password
                 Helper.showNotification("Please type your Password!");
            }
        }else{
            //username
             Helper.showNotification("Username should not be empty!");
        }
    }else{
         Helper.showNotification("Type your full Name!");
    }
        
    }//GEN-LAST:event_btn_rigesterActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked

       login l = new login();
        this.setVisible(false);
       l.setVisible(true);
      
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rigester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rigester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rigester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rigester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rigester().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_rigester;
    private javax.swing.ButtonGroup btng__auth;
    private javax.swing.JRadioButton jEditor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jb_user;
    private javax.swing.JRadioButton jrb_admin;
    private javax.swing.JPasswordField pf_password;
    private javax.swing.JPasswordField ps_confirm;
    private javax.swing.JTextField tf_fullName;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables
}
